### ISSUE TITLE
Links between publications

### ISSUE THREAD

**Issue by mikekestemont** [emanjavacas/bntl#12]
On Zotero, the data managers are entring links between publications (e.g. a book is linked to its book reviews). We would like to expert this somehow and display these links in the BNTL search interface too. It is not yet clear to us how this is technically possible, and on the FAQ of Zotero there are no real answers given to this problem. We will be looking into this. Nonetheless there should be a field on the record-page “related to” with a hyperlink to the related record (maybe this is something to keep in mind for later).

**Comment by mikekestemont** [comment]
It seems like we can also export to RDF (Bibliographic ontology RDF), and this XML seems to contain the URIs that we need (these uniquely identify bibliographic entries). @eva or @carl : can you check whether you are able to export the collection to this format and forward us an example file?

**Comment by evadecooman** [comment]
Here's an example of the RDF data and the Zotero outcome:

![image](https://github.com/user-attachments/assets/80332ade-ac49-46a0-a733-cd71433498b3)
![image](https://github.com/user-attachments/assets/4b7eb3dd-a01e-4e10-813d-f84b85b17282)
![image](https://github.com/user-attachments/assets/8784cd3a-c078-4a32-b077-32a1c5498c74)

**Comment by evadecooman** [comment]
This does not give a unique code i think, not like with the Zutilo-extension.

**Comment by evadecooman** [comment]
A comparison between the outcome on Zotero and the Bibliographic Ontology RDF file:

![image](https://github.com/user-attachments/assets/d3a1c73d-0831-4c17-8ccc-7029292dbf81)
![image](https://github.com/user-attachments/assets/659b1399-674c-4a2a-9837-077c9c1d6bf6)
![image](https://github.com/user-attachments/assets/ef8a79ce-fcf6-407f-8cf0-f42528bde456)
![image](https://github.com/user-attachments/assets/9ee660af-a316-43ea-9251-e8784b33196c)

**Comment by mikekestemont** [comment]
@evadecooman This format seems the way to go as it contains unique identifiers for each item. We should check whether this code remains stable after editing it (but I think this will be fine). Can you provide Enrique with a larger dump in this new format?

**Comment by evadecooman** [comment]
@mikekestemont OK great, what about 10.000 items ?

**Comment by mikekestemont** [comment]
Sure -- just make sure that the publications that you added links to are part of them

**Comment by evadecooman** [comment]
Do you mean the related items? I will!

**Comment by evadecooman** [comment]
I will send it via email,I cannot upload it here.
