### ISSUE TITLE
mix-up document types

### ISSUE THREAD

**Issue by evadecooman** [emanjavacas/bntl#14]
In the RIS-code all journal **articles** are defined as JOUR. The website portrays these items as complete magazine-items, which they are not (see https://bntl.flw.uantwerpen.be/item?doc_id=66daa944724fad3a6c2e10d4 / ![image](https://github.com/user-attachments/assets/a2d9ee73-d5b8-4df4-9b07-86b7dbf4339d). Here is the RIS-code: 

TY  - JOUR
PY  - 1948
TI  - Twee fragmenten uit een berijmd Middelnederlandsch morgengebed
AB  - Bevat transcriptie en facsimiles van hs. Koninklijke Bibliotheek, Brussel, IV 750 (olim Brussel, Algemeen Rijksarchief, hs. 4489).
AU  - Gorissen, Pieter
KW  - Jhesus Kerst van hemelrike
KW  - O Vader zone helich gheest
SP  - 161
DB  - Bibliografie van de Nederlandse Taal- en Literatuurwetenschap (BNTL)
SN  - 0040-7550
N2  - Gorissen, P. Twee fragmenten uit een berijmd Middelnederlandsch morgengebed. In: Tijdschrift voor Nederlandse taal- en letterkunde (Leiden): 65 ([1947]-1948) 3 (1948) 161-167.
EP  - 167
JO  - Tijdschrift voor Nederlandse taal- en letterkunde
VL  - 65
IS  - 3
LB  - success
ER  - 

JOUR in the RIS-code = Tijdschriftartikel
JFULL in the RIS-code = Speciale tijdschriftaflevering = special issue (these are now portrayed as journal articles, which is not correct)

**Comment by emanjavacas** [comment]
"The website portrays these items as complete magazine-items," do you mean that because of the image or the text?

**Comment by emanjavacas** [comment]
This is the mapping I am using right now: https://github.com/emanjavacas/bntl/blob/main/static/templates/record.html#L3-L10

**Comment by evadecooman** [comment]
It's both the image and the text. I see that there has been a mistake. We agreed with Mike not to have individual items for complete magazines on the new website. This is the correct mapping. 

'ADVS': "Audio",
    'BOOK': "Boek",
    'CHAP': "Artikel uit Boek",
    'EJOUR': "Website",
    **'JFULL': "Speciaal tijdschriftnummer",
    'JOUR': "Tijdschriftartikel",**
    'WEB': "Website"
