### ISSUE TITLE
Title descriptions: our proposition

### ISSUE THREAD

**Issue by evadecooman** [emanjavacas/bntl#15]
This is our proposition for a new item-notation for more uniformity, I hope this is (a little bit) clear to you!

The items in the list are displayed as their N2-form in the RIS-code (= like in the old BNTL / full description from old BNTL):
Old
![image](https://github.com/user-attachments/assets/ab0ae0b8-1d44-4683-9362-ea57e3bfe782)

New
![image](https://github.com/user-attachments/assets/65945923-e6d8-4d67-b153-096fe606f0f2)

In the past a lot of different citation formulas were used; now we want uniformity. The string by which the item is displayed in the list should be a normalized and uniform formula, consisting of building blocks from the RIS-code (this "code" will be different for each document type though). We suggest following formulas 

**1. JOUR:** [AU]. [TI]. In: [JO]: [VL] ([PY]) [IS], [SP]-[EP]. (So no more place of publication or month/period of issue) 
- Gorissen, P. Twee fragmenten uit een berijmd Middelnederlandsch morgengebed. In: Tijdschrift voor Nederlandse taal- en letterkunde: 65 (1948) 3, 161-167.

RIS-code
TY  - JOUR
PY  - 1948
TI  - Twee fragmenten uit een berijmd Middelnederlandsch morgengebed
AB  - Bevat transcriptie en facsimiles van hs. Koninklijke Bibliotheek, Brussel, IV 750 (olim Brussel, Algemeen Rijksarchief, hs. 4489).
AU  - Gorissen, Pieter
KW  - Jhesus Kerst van hemelrike
KW  - O Vader zone helich gheest
SP  - 161
DB  - Bibliografie van de Nederlandse Taal- en Literatuurwetenschap (BNTL)
SN  - 0040-7550
N2  - Gorissen, P. Twee fragmenten uit een berijmd Middelnederlandsch morgengebed. In: Tijdschrift voor Nederlandse taal- en letterkunde (Leiden): 65 ([1947]-1948) 3 (1948) 161-167.
EP  - 167
JO  - Tijdschrift voor Nederlandse taal- en letterkunde
VL  - 65
IS  - 3
LB  - success
ER  -

**2. BOOK (with AU = normal author)**: [AU]. [TI]. [CY]: [PB], [PY]. [EP] p. 
-	Gelder, Roelof van. Dichter in de jungle: John Gabriel Stedman 1744-1797. Amsterdam/Antwerpen: Atlas Contact, 2018. 400 p.
-	See here: in case of two authors: use [AU] & [AU] / in case of more: [AU], [AU], …, [AU] & [AU].

RIS-code: 
TY  - BOOK
PY  - 2018
TI  - Dichter in de jungle: John Gabriel Stedman 1744-1797
AB  - ISBN: 978-90-450-3272-6. P. 15-19 Voorwoord; p. 351-379 Noten; p. 381-391 Bronnen en literatuur; p. 393-394 Illustratieverantwoording; p. 396-400 Personenregister.
Y2  - 07-12-2023
AU  - Gelder, Roelof van
KW  - slavernij
KW  - reisverhaal
EP    400
DB  - Bibliografie van de Nederlandse Taal- en Literatuurwetenschap (BNTL)
N2  - Gelder, Roelof van. Dichter in de jungle: John Gabriel Stedman 1744-1797. Amsterdam/Antwerpen: Atlas Contact, 2018. 400 p.
PB  - Atlas Contact
CY  - Amsterdam/Antwerpen
ER  -

**3. BOOK (with A2 = editor(s))**: [A2] (red.). [TI]. [CY]: [PB], [PY]. [EP] p. 
-	Newman, Abigail D. & Nijkamp, Lieneke (red.). Undressing Rubens: fashion and painting in seventeenth-century Antwerp. London: Harvey Miller, 2019. 228 p.
-	See here: in case of two editors: use [A2] & [A2] / in case of more: [A2], [A2], …, [A2] & [A2].

RIS-code
TY  - BOOK
PY  - 2019
TI  - Undressing Rubens: fashion and painting in seventeenth-century Antwerp
AB  - ISBN-13 978-1-912554-22-5.
Y2  - 25-01-2024
KW  - kunstgeschiedenis
KW  - mode
KW  - Antwerpen
DB  - Bibliografie van de Nederlandse Taal- en Literatuurwetenschap (BNTL)
SN  - -13
A2  - Newman, Abigail D.
A2  - Nijkamp, Lieneke
N2  - Undressing Rubens: fashion and painting in seventeenth-century Antwerp; (eds.) Abigail D. Newman & Lieneke Nijkamp. London: Harvey Miller, 2019. 228 p.
EP  - 228
PB  - Harvey Miller
CY  - London
LB  - success
RN  - Recensies: Magnus, Hannelore. "Inde sottigheydt van al syn hooverdyen": exploring the value of Southern-Netherlandish moralising, satirical and other written sources (1625-1700) to the study of the history of costume. In: Undressing Rubens: fashion and painting in seventeenth-century Antwerp; Abigail D. Newman & Lieneke Nijkamp (eds.). London: Harvey Miller, 2019, p. 47- 70. | Du Mortier, Bianca M. In search of the origins of the huik: did the Spanish play a part in its introduction? In: Undressing Rubens: fashion and painting in seventeenth-century Antwerp; Abigail D. Newman & Lieneke Nijkamp (eds.). London: Harvey Miller, 2019, p. 161- 182. | Watteeuw, Bert. Material girl: Helena Fourment wearing a huyck. In: Undressing Rubens: fashion and painting in seventeenth-century Antwerp; Abigail D. Newman & Lieneke Nijkamp (eds.). London: Harvey Miller, 2019, p. 183- 224.
ER  - 

**4. Book Chapter**: [A1]. [TI]. In: [A2] (red.). [T2]. [CY]: [PB], [PY], p. [SP]-[EP].
-	Magnus, Hannelore. "Inde sottigheydt van al syn hooverdyen": exploring the value of Southern-Netherlandish moralising, satirical and other written sources (1625-1700) to the study of the history of costume. In: Newman, Abigail D. & Nijkamp, Lieneke (red.). Undressing Rubens: fashion and painting in seventeenth-century Antwerp. London: Harvey Miller, 2019, p. 47-70.

RIS-code
TY  - CHAP
PY  - 2019
TI  - "Inde sottigheydt van al syn hooverdyen": exploring the value of Southern-Netherlandish moralising, satirical and other written sources (1625-1700) to the study of the history of costume
Y2  - 25-01-2024
KW  - thema mode
KW  - Bie, Cornelis de
KW  - Bocstel, Henrick Aerts van
KW  - Bourgoingne, Anton van
KW  - Cauwe, Franciscus
KW  - Josephus a Sancta Barbara
KW  - Ogier, Willem (auteur)
KW  - Poirters, Adriaan
DB  - Bibliografie van de Nederlandse Taal- en Literatuurwetenschap (BNTL)
A1  - Magnus, Hannelore
A2  - Newman, Abigail D.
A2 -  Nijkamp, Lieneke
N2  - Magnus, Hannelore. "Inde sottigheydt van al syn hooverdyen": exploring the value of Southern-Netherlandish moralising, satirical and other written sources (1625-1700) to the study of the history of costume. In: Undressing Rubens: fashion and painting in seventeenth-century Antwerp; Abigail D. Newman & Lieneke Nijkamp (eds.). London: Harvey Miller, 2019, p. 47- 70.
T2  - Undressing Rubens: fashion and painting in seventeenth-century Antwerp
SP  - 47
EP  - 70
PB  - Harvey Miller
CY  - London
LB  - success
C3  - Undressing Rubens: fashion and painting in seventeenth-century Antwerp; (eds.) Abigail D. Newman & Lieneke Nijkamp. London: Harvey Miller, 2019. 228 p.
ER  -

**5. EJOUR**: [AU]. [TI]. Op: [JO]: [VL].
-	If there is no VL, PY is also good.
-	Peppelenbos, Coen. Laten we het schrijfonderwijs opheffen. Op: Tzum: geplaatst op 8.09.2024.

RIS-code:
TY  - JOUR
TI  - Laten we het schrijfonderwijs opheffen
AU  - Peppelenbos, Coen
T2  - Tzum
DA  - 2024///
PY  - 2024
VL  - Geplaatst op 8.09.2024
UR  - https://www.tzum.info/2024/09/column-coen-peppelenbos-laten-we-het-schrijfonderwijs-opheffen/
KW  - schrijfonderwijs
ER  - 

**6. WEBSITE**: [AU]. [TI]. [PY].
-	Doek, Alice. De bibliotheek van Kees Fens. 2012.

RIS-code
TY  - WEB
PY  - 2012
TI  - De bibliotheek van Kees Fens
AB  - Dit bestand biedt een digitale weergave van De bibliotheek van Kees Fens onder hoofdredactie van Alice Doek, met een bibliografie op krantenartikelen van Kees Fens van 1954 tot 2008. Het overzicht werd niet eerder gepubliceerd.
UR  - http://www.dbnl.org/tekst/doek005bibl01_01/index.php
Y2  - 19-03-2012
AU  - Doek, Alice
KW  - Fens, Kees (auteur)
KW  - particuliere bibliotheken
DB  - Bibliografie van de Nederlandse Taal- en Literatuurwetenschap (BNTL)
N2  - De bibliotheek van Kees Fens; hoofdredactie. Doek, Alice. Leiden: DBNL, 2012.
PB  - DBNL
CY  - Leiden
LB  - success
ER  -

**7. JFULL (Speciale tijdschriftaflevering)**: [TI]. Speciaal nummer van: [JO]: [VL] ([PY]) [IS], [SP]-[EP].
-	Oorlog & Vertalen. Speciaal nummer van: Filter: 24 (2017) 3, 3-42.

RIS-code
TY  - JFULL
PY  - 2017
TI  - Oorlog & Vertalen
AB  - P. 3-5 Oorlog & vertalen: bij wijze van inleiding, door de redactie (p. 5 Bibliografie).
UR  - https://www.tijdschrift-filter.nl/jaargangen/2017/243/oorlog-vertalen-bij-wijze-van-inleiding-3-5/
Y2  - 07-12-2023
KW  - thema oorlog
KW  - literair vertalen
KW  - Tweede Wereldoorlog
KW  - jodenvervolging
DB  - Bibliografie van de Nederlandse Taal- en Literatuurwetenschap (BNTL)
N2  - Oorlog & Vertalen. Nijmegen: Uitgeverij Vantilt. 39 p. Speciaal gedeelte van: Filter (Nijmegen): 24 (2017) 3 (sep) 3-42.
EP  - 39
PB  - Uitgeverij Vantilt
CY  - Nijmegen
VL  - 24
IS  - 3
LB  - success
C4  - Artikels: Spiessens, Anneleen. De ironische vertaling: "Kommandant in Auschwitz". In: Oorlog & Vertalen. Speciaal gedeelte van: Filter (Nijmegen): 24 (2017) 3 (sep) 6-15. | Storm, Marjolijn. Op zoek naar een voetnoot - Irene Kafka. In: Oorlog & Vertalen. Speciaal gedeelte van: Filter (Nijmegen): 24 (2017) 3 (sep) 16-25. | Degeest, Sien. Taalman in oorlogstijd: Vlaamse tolken tijdens de bezetting van België (1940-1945). In: Oorlog & Vertalen. Speciaal gedeelte van: Filter (Nijmegen): 24 (2017) 3 (sep) 26-33. | Brems, Elke en Jan Ceuppens. Oorlog en cultureel geheugen: Hölderlinherdenkingen in Vlaanderen. In: Oorlog & Vertalen. Speciaal gedeelte van: Filter (Nijmegen): 24 (2017) 3 (sep) 34-42.
ER  -

**8. ADVS**: [AU]. [TI]. [CY]: [PB], [PY].
-	Veldstra, Bert & Denys, Ingrid. Concordantie op de verzamelde gedichten van Gerrit Achterberg. Wilnis: AVE uitgever, 2012.

RIS-code
TY  - ADVS
PY  - 2012
TI  - Concordantie op de verzamelde gedichten van Gerrit Achterberg
AB  - ISBN 978-90-818653-0-2. 1 cd-rom.
Y2  - 07-05-2012
AU  - Veldstra, Bert
AU  - Denys, Ingrid
KW  - Achterberg, Gerrit (auteur)
DB  - Bibliografie van de Nederlandse Taal- en Literatuurwetenschap (BNTL)
SN  - 978-90-818653-0-2
N2  - Concordantie op de verzamelde gedichten van Gerrit Achterberg;  bezorgd door Bert Veldstra en Ingrid Denys. Wilnis: AVE uitgever, 2012.
PB  - AVE uitgever
CY  - Wilnis
LB  - success
ER  -

**Comment by evadecooman** [comment]
Hi Enrique,

Yes that is a problem that happens often with the E-journals; sometimes the RIS is not completely correct. Could it be possible to flag these items (where some fields have no value) with some kind of "trefwoord"/keyword? That way, we will find these cases easier and can correct them individually. This problem happens at all document type at some point by the way.

As for the other problem of the mapping; it's both the image and the text. I see that there has been a mistake. We agreed with Mike not to have individual items for complete magazines on the new website. This is the correct mapping.

'ADVS': "Audio",
    'BOOK': "Boek",
    'CHAP': "Artikel uit Boek",
    'EJOUR': "Website",
    'JFULL': "Speciaal tijdschriftnummer",
    'JOUR': "Tijdschriftartikel",
    'WEB': "Website"

Lastely, would it be possible to have a chat next Friday (20/09)? Let us know if this is possibly and at what time.

Kind regards and thank you,
Eva
________________________________
Van: Enrique Manjavacas ***@***.***>
Verzonden: donderdag 12 september 2024 17:13
Aan: emanjavacas/bntl ***@***.***>
CC: Eva De Cooman ***@***.***>; Author ***@***.***>
Onderwerp: Re: [emanjavacas/bntl] Title descriptions: our proposition (Issue #15)


Like for instance in the example for EJOUR, the string lists [JO] but there's no JO in the document data.

**Comment by emanjavacas** [comment]
Hi Eva,

with respect to missing RIS values, what comes to mind is to reject them upon ingestion, and return a log file where you can identify them and fix them. If this is too harsh, you may want to specify required fields and optional fields, so I only reject documents with missing required fields. 

I've updated the mapping now. (I am still unsure if the images map correctly, but since you can see the reference type and the image, if something looks weird just let me know.

I'll mail you about meeting.
