### ISSUE TITLE
Unique Document ID through Zutilo

### ISSUE THREAD

**Issue by evadecooman** [emanjavacas/bntl#18]
Hi Enrique, I might have found a solution for the unique doc ID but i'm not sure. 

Someone on the Zotero forum suggested downloading the plug-in Zutilo, enabling more features on the app. This plug-in enabled me to copy "Select item links" and also URI's: 
![image](https://github.com/user-attachments/assets/46dd7a30-66fa-412c-8214-85eb5b765f44)

for this record for instance it gives: zotero://select/groups/5376439/items/FH6R7K8G (item links and URI is the same here)

You think you could work with something like this (i don't know how you could export this into the RIScode?)? Some people on the forum said these codes only work within Zotero and should not be used "globally" (see this forum page: https://forums.zotero.org/discussion/106183/zotero-item-id-numbers). But maybe it is enough for our problem.

There are other options proposed on the Zotero-forum, but the plug-in was mentioned the most. 

Hope this is helpful!
Eva

**Comment by emanjavacas** [comment]
This could be an option, we just need to make sure that they can be exported along.

**Comment by evadecooman** [comment]
Hi Enrique, 

I was wondering about these unique DOC IDs. We are now currently loading the complete RIS-dump onto Zotero. This is necessary because we need to correct a lot of items. Today we are starting with these adaptations. Don't you think we need to work from our export-file then? Since our items might generate different doc id's? This is just a thought I had, because I don't really know how this technically works :-)

Thank you

**Comment by emanjavacas** [comment]
close in favor of #30
