### ISSUE TITLE
Mapping reminder

### ISSUE THREAD

**Issue by evadecooman** [emanjavacas/bntl#19]
This should be the correct mapping for the different document types. We have just decided that we want EJOUR to be a "Tijdschriftartikel" as well; we will not be making a distinction between online articles and printed ones, since everything is also published online nowadays.

'ADVS': "Audio",
'BOOK': "Boek",
'CHAP': "Artikel uit boek",
'EJOUR': "Tijdschriftartikel",
'JFULL': "Speciaal tijdschriftnummer",
'JOUR': "Tijdschriftartikel",
'WEB': "Website"

**Comment by emanjavacas** [comment]
done
