### ISSUE TITLE
Delete entries

### ISSUE THREAD

**Issue by mikekestemont** [emanjavacas/bntl#2]
We need a mechanism to delete selected entries from the dataset. (Preferably browser-based.)

**Comment by emanjavacas** [comment]
I am actually worried by the fact that this would lead the database to not be easily reproducible anymore. I think we should keep the data curation more separated from the data serving. Reindexing the whole database is something that would take less than an hour (most of the time going into vector indexing anyway). Could this not be something that the curators do on zotero and eventually trigger a full reindex?

**Comment by emanjavacas** [comment]
See latest comment on #1
