### ISSUE TITLE
Optional fields

### ISSUE THREAD

**Issue by evadecooman** [emanjavacas/bntl#20]
All categories should be optional (therefore everything should be uploaded), since there will be cases in which something is rightfully so missing. Some websites for instance do not have a PB or CY. We will search in the Zotero for defaults and look/fix them up manually.

**Comment by emanjavacas** [comment]
Alright, I'll still reject documents if none of the fields required for visualizing appears. Ok??

**Comment by evadecooman** [comment]
OK, great! Thanks.
