### ISSUE TITLE
[AB] field

### ISSUE THREAD

**Issue by evadecooman** [emanjavacas/bntl#21]
The "extra information" field should be represented, it is the [AB] field. Most of the time it has value, but sometimes it is also empty.

**Comment by emanjavacas** [comment]
Sorry, but there's no AB field in the data I got. If there was it would show up as "Extra information" as per https://github.com/emanjavacas/bntl/blob/main/static/templates/record.html#L75-L82

The mapping from RIS tags to the parsed fields is here: https://github.com/MrTango/rispy/blob/main/rispy/config.py#L18-L84

**Comment by evadecooman** [comment]
Hi Enrique, a lot of our data has AB value, here is an example: 
![image](https://github.com/user-attachments/assets/0342d13d-8b70-43b8-b21f-d99e9fcd90a4)
![image](https://github.com/user-attachments/assets/cfe9ee3f-ecf3-4db5-b2ae-1fc76312b93f)
