### ISSUE TITLE
Front-page organisation

### ISSUE THREAD

**Issue by evadecooman** [emanjavacas/bntl#22]
We have some preferences about the front-page, if possible.

The text in the bigger block on the left should be placed lower on the page and also the text should be cut off. The text "We zijn benieuwd naar uw ervaringen en wensen bij het gebruik van de bibliografie. Met het invullen van de [gebruikersenquête](https://goo.gl/forms/F7g9vbzBfzj14EdS2) kan u mee nadenken over de BNTL van de toekomst." should be deleted, as well as the link "lees verder..."

The search is the most important thing to us and should be magnified a bit; we would like for the advanced search to also be displayed on the front-page.

The widget of latest added documents is nice, but we prefer a widget in which we can write things about what magazines we updated, stuff like that. (maybe even add some visuals as well in the future).

Also: "Dit dasabase maakt gebruik van Zotero" has a spelling mistake; it should be "Deze database". The two lines below this (references to the BFTL and the DBAT can be deleted as well).

Lastly, we would like another widget for our users: a text field in which they can apply suggestions (articles that have not been added yet, that we failed to see). This should just contain a field for their email and a field for their suggestion.

Thanks

**Comment by emanjavacas** [comment]
Cool, I'll adapt this. I do have an issue with putting the advanced search form in the main page. The main page is a landing page and it should explain what the website is about. If you want to go straight to the search page, or link it, you can always refer to: https://bntl.flw.uantwerpen.be/search

Lading on a search page is very UX unfriendly.

**Comment by emanjavacas** [comment]
With respect to:

"The widget of latest added documents is nice, but we prefer a widget in which we can write things about what magazines we updated, stuff like that. (maybe even add some visuals as well in the future)."

we'd have to think about how you are going to update the website then, this wasn't really forseen when I talked to Mike about the project.

**Comment by evadecooman** [comment]
Hi, 

We discussed this and we would still like to have the advanced search on the front page because the search is the most important value of the website. People never really got to the advanced search on the old BNTL, whereas it is much more efficient to do an advanced search. 

Concerning the widget: this is something we mentionned before (maybe only to Mike - if so, we're sorry).

**Comment by evadecooman** [comment]
Also (just reminding from the meeting we had): the front page should also have the text block for users to fill in recommendations for us to upload + a block to fill in their email.

thanks!

**Comment by mikekestemont** [comment]
I agree with Enrique that putting the advanced search on the home page is extremely weird from a UX point of view: we should discuss this first internally.

**Comment by mikekestemont** [comment]
- "prefer a widget in which we can write things about what magazines we updated, stuff like that. (maybe even add some visuals as well in the future)." -> This is new to me, I must admit: what do you mean exactly with a "widget"? Can you share a mockup or example? Is this meant to be just a text description of some sort? This might be hard to realize, as there is no underlying content management system or so.
- "we would like another widget for our users: a text field in which they can apply suggestions (articles that have not been added yet, that we failed to see)" -> Would it be OK if they can just email those suggestions over (so we just add "mailto:")? Or should it be a real contact form (and why)?

**Comment by mikekestemont** [comment]
We reached the compromise that the advanced search should be added to the landing page, below the current widgets (so not very central, but still fully visible on a first visit).
