### ISSUE TITLE
Distinction between AU and A2 on website

### ISSUE THREAD

**Issue by evadecooman** [emanjavacas/bntl#23]
Browsing the website we saw that there is no distinction between Authors and Editors. This distinction is not always made in the RIS - no problem, but often with books there are editors (also important for chapters where you have an author of the chapter but editors for the book). Everything that is AU should be placed in the field "Auteur(s)", the A2 field should be represented as "Redacteur(s)".

**Comment by emanjavacas** [comment]
Here you can see how this is coded right now (A2 corresponds to secondary authors as per: https://github.com/MrTango/rispy/blob/main/rispy/config.py#L21)
https://github.com/emanjavacas/bntl/blob/main/static/templates/template.html#L26-L28

**Comment by evadecooman** [comment]
OK great, because the distinction is not clear now: 

![image](https://github.com/user-attachments/assets/801ad57e-70e2-47fc-b52b-7e039a041d10)
![image](https://github.com/user-attachments/assets/3173b1e6-80ea-4a9f-8d6b-52e1aada6b39)
