### ISSUE TITLE
Copying the string

### ISSUE THREAD

**Issue by evadecooman** [emanjavacas/bntl#24]
We also noticed that there is no possibility to copy the string representing the entire item - I think users will need this. + the possibility to directly create a citation in the preferred style (like in Zotero:)

![image](https://github.com/user-attachments/assets/0a3b714a-0698-4c48-9919-545aee755c28)
![image](https://github.com/user-attachments/assets/c996a9d4-79d5-4fce-bb04-33a4e4090e55)

**Comment by emanjavacas** [comment]
This will be covered when I implement the export to citation option.
