### ISSUE TITLE
Bibliographic Ontology RDF: links?

### ISSUE THREAD

**Issue by evadecooman** [emanjavacas/bntl#26]
So the Bibliographic Ontology RDF gives a unique DOC ID, but it does not show the related items - which is a problem. It only does so for chapters which were created in Zotero, starting from a book-item (example below). It only gives the title and no ID of the related item so our problem is still not solved. 

<rdf:RDF
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns:res="http://purl.org/vocab/resourcelist/schema#"
 xmlns:ctag="http://commontag.org/ns#"
 xmlns:z="http://www.zotero.org/namespaces/export#"
 xmlns:dcterms="http://purl.org/dc/terms/"
 xmlns:bibo="http://purl.org/ontology/bibo/"
 xmlns:address="http://schemas.talis.com/2005/address/schema#"
 xmlns:foaf="http://xmlns.com/foaf/0.1/">
    <z:UserItem rdf:about="http://zotero.org/groups/5376439/items/GXU3MFSG">
        <res:resource rdf:resource="urn:isbn:978-94-014-9249-2"/>
        <ctag:tagged>
           <ctag:UserTag><ctag:label>Vlaamse beweging</ctag:label></ctag:UserTag>
        </ctag:tagged>
        <ctag:tagged>
           <ctag:UserTag><ctag:label>theater</ctag:label></ctag:UserTag>
        </ctag:tagged>
        <ctag:tagged>
           <ctag:UserTag><ctag:label>toneel</ctag:label></ctag:UserTag>
        </ctag:tagged>
    </z:UserItem>
    <bibo:BookSection rdf:about="urn:isbn:978-94-014-9249-2">
        <dcterms:title>Toneel: van wederzijdse bevruchting naar spanning en complexiteit</dcterms:title>
        <bibo:pages>536-546</bibo:pages>
        <dcterms:creator rdf:nodeID="n4"/>
        <bibo:authorList>
           <rdf:Seq><rdf:li rdf:nodeID="n4"/></rdf:Seq>
        </bibo:authorList>
        <dcterms:isPartOf>
            <bibo:EditedBook>
                <dcterms:title>Encyclopedie van de Vlaamse beweging: de synthese</dcterms:title>
                <dcterms:publisher>
                    <foaf:Organization>
                        <address:localityName>Tielt</address:localityName>
                        <foaf:name>Lanoo</foaf:name>
                    </foaf:Organization>
                </dcterms:publisher>
                <dcterms:date>2024</dcterms:date>
                <bibo:isbn13>978-94-014-9249-2</bibo:isbn13>
                <bibo:editor rdf:nodeID="n6"/>
                <bibo:editorList>
                    <rdf:Seq>
                       <rdf:li rdf:nodeID="n6"/><rdf:li rdf:nodeID="n8"/>
                    </rdf:Seq>
                </bibo:editorList>
                <bibo:editor rdf:nodeID="n8"/>
            </bibo:EditedBook>
        </dcterms:isPartOf>
    </bibo:BookSection>
    <foaf:Person rdf:nodeID="n4">
        <foaf:givenName>Karel</foaf:givenName>
        <foaf:surname>Vanhaezebrouck</foaf:surname>
    </foaf:Person>
    <foaf:Person rdf:nodeID="n6">
        <foaf:givenName>Aragorn</foaf:givenName>
        <foaf:surname>Fuhrmann</foaf:surname>
    </foaf:Person>
    <foaf:Person rdf:nodeID="n8">
       <foaf:givenName>Sarah</foaf:givenName><foaf:surname>Menu</foaf:surname>
    </foaf:Person>
</rdf:RDF>

![image](https://github.com/user-attachments/assets/9449f0af-7f8a-44b0-9a97-c1e27bfa0334)
![image](https://github.com/user-attachments/assets/1800675d-bde1-436c-80fd-17ceafa5b2da)

**Comment by mikekestemont** [comment]
See issue #12
