### ISSUE TITLE
Search and keywords

### ISSUE THREAD

**Issue by mikekestemont** [emanjavacas/bntl#5]
A way to specifically search the keywords only (with autocomplete?) and  an alphabetical list of all keywords that can be paged through. (This aims to solve the problem that there are so many keywords that users won't know what to look for.)

**Comment by emanjavacas** [comment]
Right now you can search for keywords in the advanced search, optionally using regex. Would it work if I add a autocomplete to that search box?

**Comment by mikekestemont** [comment]
Yes, an autocomplete would be great!

**Comment by emanjavacas** [comment]
I've just created one
