### ISSUE TITLE
Multiple languages

### ISSUE THREAD

**Issue by mikekestemont** [emanjavacas/bntl#8]
- [ ] Proper Dutch names for everything (including the RIS publication types, e.g. "RIS" -> "tijdschriftartikel")
- [ ] An English version of the entire website.

**Comment by emanjavacas** [comment]
Can I have a list of these proper dutch names for the publication types (and anything else that matches)?

**Comment by mikekestemont** [comment]
For the publication types you can use:
Boek - Book
Tijdschrift - Journal
Artikel uit boek - Book section
Tijdschriftartikel - Journal article
Recensie - Review
Audio - Audio recording
Website - Web page

These should cover everything?

**Comment by emanjavacas** [comment]
I am realizing this list is not exahustive. This is what's coming from the db (with a mapping to the image names that I found on the old BNTL (not sure if the mapping is right).

ADVS': "cddvd",
    'BOOK': "boek",
    'CHAP': "artikelboek",
    'EJOUR': "artikelwebpage",
    'JFULL': "artikeltijdschrift",
    'JOUR': "tijdschriftofreeks",
    'WEB': "website"

**Comment by emanjavacas** [comment]
I correct myself. It's probably exhaustive (since it's 7 vs 7 items), but I am unsure what's the correct mapping.

**Comment by emanjavacas** [comment]
It may be correct, so I am closing and if somebody complains as user I'll adjust.
